BESTILLER_INGRESS: "https://hops.intern.nav.no"
SOF_INGRESS: "https://sof.nav.no"
BEHANDLER_INGRESS: "https://behandler.nav.no"
KAFKA_POOL: "nav-prod"
env:
  KAFKA_TOPIC_BESTILLING: "helseopplysninger.rapid"
  FKR_STS_URL: "https://helseid-sts.test.nhn.no/connect/token"
  FKR_FHIR_URL: "https://hint-inet.utv.helsedir.no/kontaktregister/ekstern"
  REDIS_HOST: "redis.helseopplysninger.svc.cluster.local"
