apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-bestiller-frontend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /
  readiness:
    path: /
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /internal/prometheus
  ingresses:
    - {{hops-ingress}}
    - {{hops-ingress}}/gui
