apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-bestiller-backend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: hops-bestiller
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  image: {{image}}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: /internal/prometheus
  ingresses:
    - {{hops-ingress}}/api
    - {{hops-ingress}}/oauth2
    - {{hops-ingress}}/ws
  kafka:
    pool: {{kafka-pool}}
  env:
    - name: APP_INGRESS
      value: {{hops-ingress}}
    - name: KAFKA_TOPIC_BESTILLING
      value: {{kafka-topic-bestilling}}
    - name: KAFKA_SECURITY_ENABLED
      value: "true"
  envFrom:
    - secret: oppslag
