apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-bestiller-backend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: hops-bestiller
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  image: {{ image }}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /api/internal/is-alive
    initialDelay: 90
  readiness:
    path: /api/internal/is-ready
    initialDelay: 90
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: /api/internal/prometheus
  ingresses:
    - {{hops-ingress}}/api
    - {{hops-ingress}}/oauth2
  env:
    - name: APP_INGRESS
      value: {{hops-ingress}}
