apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-bestiller-backend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /internal/is-alive
  readiness:
    path: /internal/is-ready
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: false
    path: /internal/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: hops-bestiller
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  ingresses:
    - {{BESTILLER_INGRESS}}/api
    - {{BESTILLER_INGRESS}}/oauth2
    - {{BESTILLER_INGRESS}}/ws
  kafka:
    pool: {{KAFKA_POOL}}
  envFrom:
    - secret: oppslag
  accessPolicy:
    outbound:
      rules:
        - application: redis-frontend
