apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: resource-puller
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /resource-puller/internal/health
  readiness:
    path: /resource-puller/internal/health
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /resource-puller/internal/prometheus
  ingresses:
    - {{sof-ingress}}/resource-puller
