apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sof-resource-puller
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /internal/is-alive
  readiness:
    path: /internal/is-ready
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  kafka:
    pool: {{kafka-pool}}
  prometheus:
    enabled: false
    path: /internal/prometheus
  env:
    - name: KAFKA_TOPIC_BESTILLING
      value: {{kafka-topic-bestilling}}
  ingresses:
    - {{sof-ingress}}/resource-puller

