apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-behandler-backend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: {{kafka-pool}}
  ingresses:
    - {{behandler-ingress}}/api
  env:
    - name: REDIS_HOST
      value: redis.helseopplysninger.svc.cluster.local
  accessPolicy:
    outbound:
      rules:
        - application: redis
