apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-behandler-backend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{image}}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /internal/is-alive
  readiness:
    path: /internal/is-ready
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: false
    path: /internal/prometheus
  kafka:
    pool: {{kafka-pool}}
  ingresses:
    - {{behandler-ingress}}/api
    - {{behandler-ingress}}/callback
  env:
    - name: REDIS_HOST
      value: redis.helseopplysninger.svc.cluster.local
  accessPolicy:
    outbound:
      rules:
        - application: redis
  envFrom:
    - secret: helseid
