apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sof-skjema
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: '{{image}}'
  port: 2022
  team: helseopplysninger
  liveness:
    path: /
  readiness:
    path: /
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /internal/prometheus
  ingresses:
    - {{SOF_INGRESS}}
